baseURL = 'https://dragonchu.github.io/'
languageCode = 'zh'
title = 'Dragonchu Blog'
theme = "PaperMod"

# enable search
[outputs]
  home = ["HTML", "RSS", "JSON"]
[[menu.main]]
  identifier = "search"
  name = "搜索"
  url = "/search/"
  weight = 2

[params]
    ShowCodeCopyButtons = true
    ShowReadingTime = true